# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: Rosettasciio Reader
email: jules.vanaret@epfl.ch
full_name: jules-vanaret
github_repository_url: provide later
github_username_or_organization: jules-vanaret
include_reader_plugin: true
include_sample_data_plugin: false
include_widget_plugin: false
include_writer_plugin: true
install_dependabot: false
install_precommit: false
license: MIT
module_name: napari_rosettasciio
plugin_name: napari-rosettasciio
short_description: A plugin to use the Rosetta Reader in Napari
